export const data = [
    {
        phone: "1-124-775-7715",
        name: "Nell Marks",
        region: "Gorontalo",
        country: "Germany",
    },
    {
        phone: "1-651-985-7790",
        name: "Carson Doyle",
        region: "Istanbul",
        country: "Chile",
    },
    {
        phone: "1-134-718-1018",
        name: "Caleb Greer",
        region: "Opolskie",
        country: "Poland",
    },
    {
        phone: "(470) 627-0708",
        name: "Nita Villarreal",
        region: "National Capital Region",
        country: "Brazil",
    },
    {
        phone: "(576) 717-8738",
        name: "Felix Aguilar",
        region: "Lampung",
        country: "Peru",
    },
    {
        phone: "1-124-775-7715",
        name: "Nell Marks",
        region: "Gorontalo",
        country: "Germany",
    },
    {
        phone: "1-651-985-7790",
        name: "Carson Doyle",
        region: "Istanbul",
        country: "Chile",
    },
    {
        phone: "1-134-718-1018",
        name: "Caleb Greer",
        region: "Opolskie",
        country: "Poland",
    },
    {
        phone: "(470) 627-0708",
        name: "Nita Villarreal",
        region: "National Capital Region",
        country: "Brazil",
    },
    {
        phone: "(576) 717-8738",
        name: "Felix Aguilar",
        region: "Lampung",
        country: "Peru",
    },
    {
        phone: "1-124-775-7715",
        name: "Nell Marks",
        region: "Gorontalo",
        country: "Germany",
    },
    {
        phone: "1-651-985-7790",
        name: "Carson Doyle",
        region: "Istanbul",
        country: "Chile",
    },
    {
        phone: "1-134-718-1018",
        name: "Caleb Greer",
        region: "Opolskie",
        country: "Poland",
    },
    {
        phone: "(470) 627-0708",
        name: "Nita Villarreal",
        region: "National Capital Region",
        country: "Brazil",
    },
    {
        phone: "(576) 717-8738",
        name: "Felix Aguilar",
        region: "Lampung",
        country: "Peru",
    },
    {
        phone: "1-124-775-7715",
        name: "Nell Marks",
        region: "Gorontalo",
        country: "Germany",
    },
    {
        phone: "1-651-985-7790",
        name: "Carson Doyle",
        region: "Istanbul",
        country: "Chile",
    },
    {
        phone: "1-134-718-1018",
        name: "Caleb Greer",
        region: "Opolskie",
        country: "Poland",
    },
    {
        phone: "(470) 627-0708",
        name: "Nita Villarreal",
        region: "National Capital Region",
        country: "Brazil",
    },
    {
        phone: "(576) 717-8738",
        name: "Felix Aguilar",
        region: "Lampung",
        country: "Peru",
    },
    {
        phone: "1-124-775-7715",
        name: "Nell Marks",
        region: "Gorontalo",
        country: "Germany",
    },
    {
        phone: "1-651-985-7790",
        name: "Carson Doyle",
        region: "Istanbul",
        country: "Chile",
    },
    {
        phone: "1-134-718-1018",
        name: "Caleb Greer",
        region: "Opolskie",
        country: "Poland",
    },
    {
        phone: "(470) 627-0708",
        name: "Nita Villarreal",
        region: "National Capital Region",
        country: "Brazil",
    },
    {
        phone: "(576) 717-8738",
        name: "Felix Aguilar",
        region: "Lampung",
        country: "Peru",
    },
    {
        phone: "1-124-775-7715",
        name: "Nell Marks",
        region: "Gorontalo",
        country: "Germany",
    },
    {
        phone: "1-651-985-7790",
        name: "Carson Doyle",
        region: "Istanbul",
        country: "Chile",
    },
    {
        phone: "1-134-718-1018",
        name: "Caleb Greer",
        region: "Opolskie",
        country: "Poland",
    },
    {
        phone: "(470) 627-0708",
        name: "Nita Villarreal",
        region: "National Capital Region",
        country: "Brazil",
    },
    {
        phone: "(576) 717-8738",
        name: "Felix Aguilar",
        region: "Lampung",
        country: "Peru",
    },
    {
        phone: "1-124-775-7715",
        name: "Nell Marks",
        region: "Gorontalo",
        country: "Germany",
    },
    {
        phone: "1-651-985-7790",
        name: "Carson Doyle",
        region: "Istanbul",
        country: "Chile",
    },
    {
        phone: "1-134-718-1018",
        name: "Caleb Greer",
        region: "Opolskie",
        country: "Poland",
    },
    {
        phone: "(470) 627-0708",
        name: "Nita Villarreal",
        region: "National Capital Region",
        country: "Brazil",
    },
    {
        phone: "(576) 717-8738",
        name: "Felix Aguilar",
        region: "Lampung",
        country: "Peru",
    },
    {
        phone: "1-124-775-7715",
        name: "Nell Marks",
        region: "Gorontalo",
        country: "Germany",
    },
    {
        phone: "1-651-985-7790",
        name: "Carson Doyle",
        region: "Istanbul",
        country: "Chile",
    },
    {
        phone: "1-134-718-1018",
        name: "Caleb Greer",
        region: "Opolskie",
        country: "Poland",
    },
    {
        phone: "(470) 627-0708",
        name: "Nita Villarreal",
        region: "National Capital Region",
        country: "Brazil",
    },
    {
        phone: "(576) 717-8738",
        name: "Felix Aguilar",
        region: "Lampung",
        country: "Peru",
    },
    {
        phone: "1-124-775-7715",
        name: "Nell Marks",
        region: "Gorontalo",
        country: "Germany",
    },
    {
        phone: "1-651-985-7790",
        name: "Carson Doyle",
        region: "Istanbul",
        country: "Chile",
    },
    {
        phone: "1-134-718-1018",
        name: "Caleb Greer",
        region: "Opolskie",
        country: "Poland",
    },
    {
        phone: "(470) 627-0708",
        name: "Nita Villarreal",
        region: "National Capital Region",
        country: "Brazil",
    },
    {
        phone: "(576) 717-8738",
        name: "Felix Aguilar",
        region: "Lampung",
        country: "Peru",
    },
    {
        phone: "1-124-775-7715",
        name: "Nell Marks",
        region: "Gorontalo",
        country: "Germany",
    },
    {
        phone: "1-651-985-7790",
        name: "Carson Doyle",
        region: "Istanbul",
        country: "Chile",
    },
    {
        phone: "1-134-718-1018",
        name: "Caleb Greer",
        region: "Opolskie",
        country: "Poland",
    },
    {
        phone: "(470) 627-0708",
        name: "Nita Villarreal",
        region: "National Capital Region",
        country: "Brazil",
    },
    {
        phone: "(576) 717-8738",
        name: "Felix Aguilar",
        region: "Lampung",
        country: "Peru",
    },
    {
        phone: "1-124-775-7715",
        name: "Nell Marks",
        region: "Gorontalo",
        country: "Germany",
    },
    {
        phone: "1-651-985-7790",
        name: "Carson Doyle",
        region: "Istanbul",
        country: "Chile",
    },
    {
        phone: "1-134-718-1018",
        name: "Caleb Greer",
        region: "Opolskie",
        country: "Poland",
    },
    {
        phone: "(470) 627-0708",
        name: "Nita Villarreal",
        region: "National Capital Region",
        country: "Brazil",
    },
    {
        phone: "(576) 717-8738",
        name: "Felix Aguilar",
        region: "Lampung",
        country: "Peru",
    },
];
